server:
  port: 3000
eureka:                       # redis也是eureka的客户端
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
spring:
  application:
    name: atguigu-crowd-redis
  redis:
    host: 192.168.241.130